### ISSUE TITLE
Moving from MySQL to PostgreSQL

### ISSUE THREAD

**Issue by hrhotz** [bgruening/training-material#105]
does it really make sense to have a separte chapter/tutorial about this ? why not keep it as part of the "Galaxy Database schema" ? 
I consider it as a very advance topic, which will be difficult to teach, and not of general interest - IMHO.

Everybody should use PostgreSQL from the start nowadays.

Hans-Rudolf

**Comment by bgruening** [comment]
I tend to agree! You are the admin maintainer, so go ahead :)

**Comment by bebatut** [comment]
So we can close this issue?
