### ISSUE TITLE
add admin training material

### ISSUE THREAD

**Issue by bgruening** [bgruening/training-material#12]
@hrhotz I will add this issue to you :)

**Comment by hrhotz** [comment]
ok

**Comment by hrhotz** [comment]
just double checking: will this be a extra folder or part of the "Admin-Corner" ?

**Comment by bgruening** [comment]
AdminCorner I think. Open for other suggestions. :-)

**Comment by bgruening** [comment]
I think we have some initial material to make the case, that this repo is also for Admin and Dev training.

Thanks @hrhotz
