### ISSUE TITLE
Templates for the scheme

### ISSUE THREAD

**Issue by bebatut** [bgruening/training-material#126]
Hi,

It is nice also to have some scheme to sum up the pipeline used during the tutorial, like flowcharts

I thought to use [yED](http://www.yworks.com/products/yed) to easily build scheme.

What do you think?

Bérénice

**Comment by ValentinMarcon** [comment]
I will try to create one example for [issue123](https://github.com/bgruening/training-material/issues/123)

**Comment by ValentinMarcon** [comment]
I tried two pipeline scheme (Grey is for subpart):

1
![workflow1](https://cloud.githubusercontent.com/assets/10078639/19192181/b195caec-8ca5-11e6-812e-4095f699e665.png)
2
![workflow2](https://cloud.githubusercontent.com/assets/10078639/19192182/b19aae9a-8ca5-11e6-9218-e962b37c5a9a.png)

**Comment by bgruening** [comment]
I prefer the first one :)

**Comment by friedue** [comment]
yep, definitely the first one. with less harsher colors ;) (Galaxy green? blue?)

**Comment by ValentinMarcon** [comment]
I will take all advice for color and disposal yep :)

**Comment by bgruening** [comment]
Blue sounds good :)

**Comment by ValentinMarcon** [comment]
With the yellow, grey and dark-blue of the Galaxy logo:
![workflow](https://cloud.githubusercontent.com/assets/10078639/19193331/0071723e-8caa-11e6-8173-260636733eed.png)

**Comment by oinizan** [comment]
Whaou !

**Comment by friedue** [comment]
very nice, I like the alternating colors a lot
Is there a way to change the font? (although this looks a lot like Galaxy's font)

**Comment by bebatut** [comment]
Nice! 
What about using boxes instead of bubbles?

**Comment by ValentinMarcon** [comment]
With "NotoSans" Font (found on the css for the slides)

![workflow](https://cloud.githubusercontent.com/assets/10078639/19194140/08eacec6-8cad-11e6-980e-3f3d517fd056.png)

I will try @bebatut

**Comment by ValentinMarcon** [comment]
Most compact version (with box)

![workflow3](https://cloud.githubusercontent.com/assets/10078639/19194490/fb11c06a-8cad-11e6-99ad-0e45560678bd.png)

**Comment by oinizan** [comment]
+1

**Comment by bebatut** [comment]
As the corresponding PR #129 was merged, can we close this issue?

**Comment by bgruening** [comment]
Thanks all!
