### ISSUE TITLE
List in TeSS

### ISSUE THREAD

**Issue by dannon** [bgruening/training-material#151]
I'm going to look into maybe automatically listing these at https://tess.elixir-uk.org/ for more discoverability.

**Comment by bgruening** [comment]
duplicate of https://github.com/bgruening/training-material/issues/46

Thanks @dannon this is a great idea and we should do this asap.

**Comment by dannon** [comment]
That's what I get for making issues during talks, without scanning all the open ones first!  Yeah, it looks very doable.  I'll follow #46.
