### ISSUE TITLE
Slides are not rendering due to missing ./reveal.js/ contents

### ISSUE THREAD

**Issue by yhoogstrate** [bgruening/training-material#163]
I wanted to create slides for this repo but when I was browsing through the available examples (*/slides/*.html) I couldn't find any working prototype because a JS lib appears to be missing. Is there a guide or a working example to get me quickly started?

**Comment by bgruening** [comment]
Can you look at the chipseq or rnaseq examples?

**Comment by yhoogstrate** [comment]
Oops, I needed a recursive clone for the submodules :) Thanks!
