### ISSUE TITLE
Docker images not found?

### ISSUE THREAD

**Issue by afgane** [bgruening/training-material#168]
This page indicates a Docker image exists for each of these tutorials, however, when I tried pulling in images for the NGS mapping tutorial and the chip-seq tutorial but am getting `image not found error`:
```
$ docker run -d -p 8080:80 bgruening/galaxy-ngs-mapping-training
Unable to find image 'bgruening/galaxy-ngs-mapping-training:latest' locally
Pulling repository docker.io/bgruening/galaxy-ngs-mapping-training
docker: Error: image bgruening/galaxy-ngs-mapping-training:latest not found.
```

Poking around, I see that the README on the repo indicates only the RNA-seq and the Exome tutorials have corresponding Docker images, which seems to be the case.

Should these two be synced?

**Comment by bgruening** [comment]
One reason this training material is currently under the bgruening namespace is that everything in in a flux and WIP. The plan is indeed to have to every training a Tour and a Docker Image, we haven't done so yet. But it should be fairly easy to do so. Let me know what you need and I will create you this image.

Sorry for the inconvenience.

**Comment by afgane** [comment]
OK - that clears it up. I don't actually need anything in particular but was just trying to set up more of the flavors up in the launcher to see if things work with more than just one image - only to realize the images didn't exist so that threw me off a bit.

Anyhow, feel free to close this or keep it open as a reminder if you prefer that.

**Comment by bgruening** [comment]
Can I just give you a list of flavors that exists and that the community has developed?
