### ISSUE TITLE
Base the training material on official flavours.

### ISSUE THREAD

**Issue by bgruening** [bgruening/training-material#22]
Thinking about our Docker Images, it would probably make sense to base the training image on some official flavors?

https://github.com/bgruening/docker-recipes/tree/master/galaxy-exom-seq

Disadvantage is that in the resulting training container could contain more tools than needed. How bad is this?

ping @bebatut

**Comment by bgruening** [comment]
`startup_lite` is also part of the container already and does not need to be included here.

**Comment by hrhotz** [comment]
+1 for 'official flavors'

**Comment by bgruening** [comment]
Beginning is here: https://github.com/bgruening/training-material/pull/39
I also would like to build the images via travis and test them.

**Comment by bebatut** [comment]
Is this issue still topical?

**Comment by bebatut** [comment]
Docker
