### ISSUE TITLE
Galaxy Docker flavours for every training

### ISSUE THREAD

**Issue by bgruening** [bgruening/training-material#4]
The idea is to offer training Docker Instances for course. We could have a Docker subdir in each training course and build images automatically.

@dyusuf @nekrut what do you think.
We already started with a RNA-workbench and have one for ChIP-seq (mainly the deeptools Image).

**Comment by dyusuf** [comment]
sounds really good while I cannot be fully committed to the tasks for now. Well I can take on the tasks after we finished the galaxy course which will be between 17-18 of May.

**Comment by bgruening** [comment]
ping @dyusuf 
We will start working on this. Please have a look at the new readme file. My idea is here to offer for all trainings some such an icon, to indicate which training is available in which form.

**Comment by frederikcoppens** [comment]
Can Docker instances be linked to Cloud Launch? This would be a nice as this would allow trainees to  do "real" analyses using the same Galaxy as for training. Of course this requires a Cloud Launch with associated infrastructure behind, but this is something we can raise (if there is sufficient support)

**Comment by bgruening** [comment]
@frederikcoppens this is the plan and @afgane @nuwang are working hard to make this real.

**Comment by frederikcoppens** [comment]
Perfect! I've been inquiring for interest in Cloud Launch within ELIXIR.
I assume it's also not very complicated to provide a way to convert the Docker to a VM, as not all clouds support docker.

**Comment by bgruening** [comment]
Small update: https://github.com/bgruening/training-material/tree/master/Exome-Seq/docker

**Comment by bgruening** [comment]
@dyusuf @frederikcoppens any help appreciated. We starting to get the stone rolling!

**Comment by bebatut** [comment]
As written in the [`CONTRIBUTING.md`](https://github.com/bgruening/training-material/blob/master/CONTRIBUTING.md), every topic must have a docker image. The work has started in the PR
