### ISSUE TITLE
Galaxy Dev-Corner - Tool integration 

### ISSUE THREAD

**Issue by lecorguille** [bgruening/training-material#50]
So far, here is what we have in France about Tool integration.
https://www.dropbox.com/s/afoftkt2k103tdx/galaxy4bioinformatics-integration-partI-1.13.pdf?dl=0

We already gave this course during 3 sessions.

I aware that it's not up-to-date about Conda and that I was at that moment a little scare to base all the training on Planemo because it couldn't handle dependencies properly, was a little buggy (or it's was us?) and because we were not so many to correctly use it among the trainers, ...
And I guess it's not either complete about dataset collection.
And ...

I know that there are some on [Planemo readthedocs](http://planemo.readthedocs.io/en/latest/writing_advanced.html) But, is there other materials somewhere?

**Comment by bgruening** [comment]
It was probably not just you. Planemo had its issues but today it is stable imho and the way to go for tool development. I also deprecated my training material in favor of the official planemo docs. They are now linked here: https://github.com/bgruening/training-material/tree/master/Dev-Corner

Your link does not work for me, sorry.

**Comment by lecorguille** [comment]
@bgruening Pydio is broken 😭 I have just update the link.

**Comment by bgruening** [comment]
Oh I like the slides. How can we combine the slides with the planemo docs? Maybe converting the slides as introduction so that these can be shown in between? But the hands-on is from the read-the-docs?

**Comment by lecorguille** [comment]
Ok
I will try to compare the two. If you want you can point me some ranges of slides which can be interesting to kept?

Then I can split ours and transcript some parts in Markdown.

**Comment by bgruening** [comment]
I like the general introduction slides, some slides about the planemo webinterface and this kind of things.
I looks like a very nice totorial overall, I just think that keeping the real tutorial in planemo and next to best-practice-guidline is future proof. Some additional slides are always good. What do you think?

**Comment by lecorguille** [comment]
Sound good!
