### ISSUE TITLE
Galaxy training contribution fest - 6-7th October

### ISSUE THREAD

**Issue by bgruening** [bgruening/training-material#58]
Dear training enthusiast,

The Galaxy Training Network (GTN) is planning a contribution fest to consolidate our training material and improve the overall training experience in Galaxy on the 6.-7th October 2016! 

More information about this project can be found here:
https://gist.github.com/bgruening/a54a8600c5cddca82424ad13569708c3

and a small presentation is here:
http://bgruening.github.io/training-material/shared/slides/project_presentation#/

This will be an online contribution fest and the fun to contribute should be priority one! There is enough to work on in all areas, from programming to fix spelling mistakes. So everyone is welcome to improve the Galaxy training material.

## Organisation

We will coordinate ourselves over Gitter: https://gitter.im/Galaxy-Training-Network/Lobby
In addition we will be available at this hangout https://hangouts.google.com/call/bapluwa3s5deveo5flrcwqzqpme
A list of this that can be worked on during the contribution fest can be found here: https://github.com/bgruening/training-material/issues

## How to start contributing? 

A small checklist to help you with this contribution fest
- Create a GitHub account
- Check the [`CONTRIBUTING.md`](https://github.com/bgruening/training-material/blob/master/CONTRIBUTING.md)
- Become familiar with this repository structure
- Connect to the [Gitter chat](https://gitter.im/Galaxy-Training-Network/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) with your GitHub account and say hello :)
- Check out the [issues](https://github.com/bgruening/training-material/issues) and [PR](https://github.com/bgruening/training-material/pulls)
- Add you on the [`CONTRIBUTORS.md`](https://github.com/bgruening/training-material/blob/master/CONTRIBUTORS.md)
- Add you on the [Galaxy map](https://github.com/bgruening/galaxy-maps)
- Register for the [hacktoberfest](https://hacktoberfest.digitalocean.com/)
- (If you like) Assign yourself as a [maintainer of a topic](https://github.com/bgruening/training-material/issues/63) and take over responsibilities
- Assign yourself to an issue or a PR when you find one (or create one) and tell it on Gitter
- Ask if you have any question

Ciao,
Bérénice and Bjoern

**Comment by jmchilton** [comment]
Cool beans - I'll try to work on https://github.com/galaxyproject/galaxy/pull/2283 during this. I don't know how that would fit into your master plan but it is Markdown and HTML slides and important documentation - but it is not reveal.js though. The good part of the approach though is that it seems to fit into Sphinx well.
 Maybe we should harmonize approaches.

**Comment by friedue** [comment]
sounds great! anybody in the New York City area who'd like to meet up for this?

**Comment by bgruening** [comment]
@jmchilton sounds good. Currently we agreed upon reveal.js here: https://github.com/bgruening/training-material/issues/8 But I think as everythin is markdown we can inter convert everything.

@friedue great you can join!

Anyone nearby Freiburg/Germany wants to join? Afaik @hrhotz will visit us on 6th to work with us in Freiburg and others are welcome too!

**Comment by bgruening** [comment]
@vipints you are still in New York, aren't you? :)

**Comment by vipints** [comment]
Björn, Yeah I am still here in NYC :)  Planning to join for the event virtually.

**Comment by vipints** [comment]
@friedue: I am in MSKCC

**Comment by bgruening** [comment]
@friedue I kindly introduce you to @vipints! He knows TÜ!
@vipints I kindly introduce you to @friedue! She was in FR! ;)

**Comment by stevekm** [comment]
I this training material for using Galaxy, or setting up Galaxy?

**Comment by bgruening** [comment]
@stevekm both. We have collected material for admins: https://github.com/bgruening/training-material/tree/master/Admin-Corner, Users and Developers.

**Comment by stevekm** [comment]
Is there a formal step-by-step guide for Admins getting started with Docker and setting it up as a service? I looked through the items there, and have gone through the documentation in other places but so far haven't found a complete walk-through; had plans to write one myself once I figure it all out. 
Also, I had issues with the link in the readme on that page, might need to change it to this? http://galaxy.slides.com/bgruening/the-galaxy-docker-project#/

**Comment by bgruening** [comment]
@stevekm the link is working for me :( What do you see.
We have a lot of documentation about the Docker project here: https://github.com/bgruening/docker-galaxy-stable 
I hope this helps.

**Comment by stevekm** [comment]
@bgruening I think the `live` part of the URL is trying to start a live session; for me it just hangs on the first slide trying to establish a connection to your account. The URL I listed shows the slides only. 
The Docker doc's have been very useful but I've still had to pull together info from many other sources (e.g. Ansible playbooks) to get things configured; doc's for the other aspects weren't written in the context of using Docker so its been a little extra confusing to figure out how to piece everything together.

**Comment by bgruening** [comment]
@stevekm are you using this Container or developing for it/with it? The latter is indeed not covered.

**Comment by stevekm** [comment]
Right now I am trying to get the Galaxy Docker set up as a service at my institution.

**Comment by slegras** [comment]
Hi! that's a pretty nice initiative! Have you spit up the 2 days into topics; I'd like to join but I can't join the two entire days.

**Comment by bgruening** [comment]
@slegras great to see you here!
we haven't any topics, I thought everyone works on a specific training or that small groups working on a specific training over the two days. But I'm open for suggestions.
@stevekm let ma know if you get stuck and how we can improve our documentation.

**Comment by slegras** [comment]
Ok, I'll be there (on the 6th) and see to which topic(s) I can contribute :)

**Comment by stevekm** [comment]
how does an 'online contribution fest' work? Is there a website or physical location where people are meeting?

**Comment by bgruening** [comment]
We will be on gitter/IRC as you like I will open an hangout and will start with a short presentation and what we are aiming for in this project. Then everyone can start gathering together in groups, get things done, ask questions, create PR, have fun to work together :)

**Comment by lecorguille** [comment]
As I already said, I'm in to contribute on the [dev-corner](https://github.com/bgruening/training-material/issues/50)

**Comment by hrhotz** [comment]
unfortunately, I won't be able to join in person in Freiburg on Thursday, but will try to do some work in the admin corner on Thursday/Friday

**Comment by shiltemann** [comment]
I will join the hackathon as well. We have some training materials here: https://github.com/ErasmusMC-Bioinformatics/galaxy-courses, some of which we could maybe adapt/integrate here. And I can help out with the introduction, NGS, and RNA-seq topics in general as we teach those a lot ourselves too. And I could help out in dev-corner for tools/IEs/viz as well.

I would also like to see a metagenomics topic, I've started working on a galaxy training (following this repos' style) for the Mothur MiSeq SOP (http://www.mothur.org/wiki/MiSeq_SOP) with some additional visualisation steps (krona/phinch etc) ..and in the long term would like to add a training for qiime as well (but will need to work on the tools themselves first).

**Comment by bgruening** [comment]
@hrhotz too bad! I ordered already cookies ;)
@shiltemann sounds wonderful!
I have updated the description above and added a organisation section.

**Comment by devengineson** [comment]
Hi @bebatut @bgruening and all Galaxy lovers, EnginesOn, @jennydg @fjrmoreews @yvanlebras, are insterested to participate to this new hackathon time! The objectives can be for us to improve the training tutorial for RAD-Seq and for Multi-QC developped by @yvanlebras and @cmonjeau. This will also be the opportunity for Jennifer, future leader of the company, to get involved in the community and get familiar with this type of event..... 
@bgruening is your cookies sendable by ftp ;) ?

**Comment by bgruening** [comment]
@devengineson what can I say? Engine On! Let's rock the Galaxy training world!

**Comment by jennydg** [comment]
Hi @bebatut @bgruening! @devengineson will be represented by myself, with help from @yvanlebras, @fjrmorreews, @cmonjeau but I will probably not be able to cover the whole 2 days. I already know I won't be available tomorrow morning.

**Comment by bgruening** [comment]
@jennaj sure thing! The aim is to have fun and work with friends don't feel bad if you can not join :)

**Comment by yvanlebras** [comment]
@bgruening I think there is a Jenni mistake ;) in your last message between @jennaj and @jennydg 

I like your hfawwf (have fun and work with friends) concept !

**Comment by bgruening** [comment]
Upps, you are right! @jennydg my bad sorry. `hfawwf`!

**Comment by gmauro** [comment]
Hi all, I will try to join the hackathon both days with.

**Comment by bgruening** [comment]
@gmauro great! See you tomorrow!

**Comment by tnabtaf** [comment]
I'll join tomorrow and Friday.  I'm Pacific US time, so will be on the tail end of both days.

**Comment by stevekm** [comment]
are there details up yet about how/when to join?

**Comment by bgruening** [comment]
@stevekm please read the issue above. I have tried to collect all information's there.
Moreover, there is no `when`. People from all over the world will join and depending on the timezone this can vary a lot. Just join us on gitter and assign yourself to one of the https://github.com/bgruening/training-material/issues or contribute your own training material! 
HFAWWF - (have fun and work with friends) :)

**Comment by stevekm** [comment]
also @friedue @vipints I am in NYC too let me know if there's a meetup for this

**Comment by jennaj** [comment]
I posted this to Biostars in hopes of attracting some sci users. Hope Ok! https://biostar.usegalaxy.org/p/19971/

**Comment by bgruening** [comment]
@jennaj more than ok! Fantastic! Thanks!

**Comment by bgruening** [comment]
Ok Europe we will start the contribution fest! :)

**Comment by friedue** [comment]
@stevekm Vipin and I will join tomorrow, I've booked a room at Weill Cornell for this (send me an email to frd2007 at med.cornell.edu to get the exact location, would be great to have you around, too!)

**Comment by bgruening** [comment]
Hi all,

I'm so sorry we wanted to publish a nice writeup about this great event, but we are swamped with preparation for the Swiss/German Galaxy workshop here in Freiburg. I promise to get to this as soon as possible.... Many thanks to you all again! This was a great event and we hope to organize a similar event soon.

**Comment by yvanlebras** [comment]
Thank you Björn and Bérénice for the amazing work to help us contribute in the best way!!!!! 

I look forward to have time to finish a first complete version of the Stacks training material!!!! 

Tscüss, 

Yvan 

----- Mail original -----

> De: "Björn Grüning" <notifications@github.com>
> À: "bgruening/training-material" <training-material@noreply.github.com>
> Cc: "Yvan Le Bras" <yvan.le_bras@irisa.fr>, "Mention"
> <mention@noreply.github.com>
> Envoyé: Mardi 18 Octobre 2016 14:25:37
> Objet: Re: [bgruening/training-material] Galaxy training contribution fest -
> 6-7th October (#58)

> Hi all,

> I'm so sorry we wanted to publish a nice writeup about this great event, but
> we are swamped with preparation for the Swiss/German Galaxy workshop here in
> Freiburg. I promise to get to this as soon as possible.... Many thanks to
> you all again! This was a great event and we hope to organize a similar
> event soon.

> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub , or mute the thread .

-- 
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 
Yvan Le Bras, PhD @Yvan2935 <°))))>< 
e-Biogenouest project http://www.e-biogenouest.org 
CNRS UMR 6074 IRISA-INRIA, Campus de Beaulieu, 35042 Rennes Cedex 
tél.: +33 (0) 2 99 84 71 79 / +33 (0) 6.10.43.96.51 
yvan.le_bras@irisa.fr

**Comment by bgruening** [comment]
A little bit late but here is our summary!!!

https://docs.google.com/document/d/1pThnwvQKvdN1C0ub1QWoXcWp71QinZb_msUKHLFxfFI/pub

Thanks again!

**Comment by hrhotz** [comment]
very nice text! a big Thank you to @bebatut and @bgruening
