### ISSUE TITLE
Outline of the training material restructering

### ISSUE THREAD

**Issue by bgruening** [bgruening/training-material#6]
As discussed in the GTN BOF at GCC I will start restructuring our training material and define a common scaffold. This will happen in this repository as a playground.

In the readme file I added a few icons and a small description:

https://github.com/bgruening/training-material/blob/master/README.md

This should serve as fast indicator what a user can expect from our training material.

Ideal case: Hands-on training material, with Docker image and Galaxy tours.

I'm in contact with Frederik Coppens (@frederikcoppens) and we should be able to coordinate this with ELIXIR and get some help in restructuring and collection other materials.

As soon as (let's say) the RNA-Seq tutorial has at least a Docker container and we are happy with the structure I will move this repository over to the galaxyproject organization.

Further steps will be the integration of a template system (https://github.com/bgruening/training-material/issues/5) and getting tours better integrated.

**Comment by bgruening** [comment]
Ok, I did merged the training material from Anton in this repository. Please let me know what we can improve on the structure. We need some kind of naming convention for markdown files etc... nothing is set in stone. Let me know what you think.

**Comment by bebatut** [comment]
Reorganization of the training material is explained in the [`CONTRIBUTING.md`](https://github.com/bgruening/training-material/blob/master/CONTRIBUTING.md) and the work was started in the PR
