### ISSUE TITLE
Where to store images?

### ISSUE THREAD

**Issue by bgruening** [bgruening/training-material#7]
In a `~/shared/images` folder or next to the training material in a `./images` folder?

**Comment by friedue** [comment]
mh, I slightly gravitate towards `./images`, but if a consistent nomenclature such as `ChIPseq_image01.png` is enforced, I wouldn't mind the first solution, either

**Comment by bgruening** [comment]
I think so as well. If we all agree on this we need to move the images over into the subfolder from Anton.

**Comment by frederikcoppens** [comment]
next to the training material will cause less hassle
truly shared images (e.g. logos) could be in a shared folder on the other hand

**Comment by bgruening** [comment]
Ok, I think we have a consensus here :)
Anyone volunteering to move images around?

**Comment by bgruening** [comment]
This is now described in https://github.com/bgruening/training-material/blob/master/GUIDELINES.md
Thanks for you comments!
