### ISSUE TITLE
Slides format?

### ISSUE THREAD

**Issue by bgruening** [bgruening/training-material#8]
In which format should we host Slides?
Please vote with thumbs-up or comment with a new format, but offer an explanation.
It should be a source file format, PDF will be auto-generated from that source.

**Comment by bgruening** [comment]
__Latex__
Because we all love it and can write it.

**Comment by bgruening** [comment]
__ODT__
Because a graphical editor is super cool and I can use PPT as well.

**Comment by bgruening** [comment]
__reveal-js__
It is maintained, can be used as source with markdown and on `slides.com` offers a graphical editor.

**Comment by frederikcoppens** [comment]
As indicated, I would opt for reveal-js. 
LaTeX will be over the top for a lot of trainers in my experience.
In practice a lot of materials currently are in PPT, while we should put some best practices forward, we might need to cope with this too to get materials in (and then over time aim to convert/redo them)

**Comment by bgruening** [comment]
I'm fine with a staging area, were we collect ppts and convert them as we have time.

**Comment by hrhotz** [comment]
Though, it is a shame, but I share Frederik's concerns about LaTeX. So I like the idea of a "staging" area.

**Comment by friedue** [comment]
thumbs up for a staging area

**Comment by bgruening** [comment]
Ok we are going with reveal.js for the moment. It is markdown based and hopefully easy enough for users and developers.
