### ISSUE TITLE
(Native) English proofreading of CONTRIBUTING

### ISSUE THREAD

**Issue by bebatut** [bgruening/training-material#89]
☝  Newcomers Only

This issue is reserved for people who never contributed to Open Source before. 
We know that the process of creating a Pull Request is the biggest barrier for new contributors. 

❓ The Motivation

As most of our contributors are non-native English speakers/writers, we are looking for people willing to proofread the training material.

🎯  The goal

The [`CONTRIBUTING.md`](https://github.com/bgruening/training-material/blob/master/CONTRIBUTING.md) needs to check to find spelling or syntax errors.

📋  Step by Step

1. Claim this issue by commenting below
2. Edit the [`CONTRIBUTING.md`](https://github.com/bgruening/training-material/blob/master/CONTRIBUTING.md) with your changes after clicking on small :pencil2: in the top right)
3. Propose file change with the message `Fix spelling/syntax errors in CONTRIBUTING`
4. Ask in comments for a review :)
4. 🏁 Done 

If you are familiar with the terminal or would like to learn it, you can follow the [GitHub flow](https://guides.github.com/introduction/flow/) for 2 and 3:

- [Create a fork](https://help.github.com/articles/fork-a-repo/) of this repository on GitHub
- Clone your fork of this repository to create a local copy on your computer
- Create a new branch in your local copy for each significant change
- Commit the changes in that branch
- Push that branch to your fork on GitHub
- Submit a pull request from that branch to the [master repository](https://github.com/bgruening/training-material)
- If you receive feedback, make changes in your local clone and push to your branch on GitHub: the pull request will update automatically

🤔❓ Questions

Ping us on the [Gitter chat](https://gitter.im/Galaxy-Training-Network/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link)

**Comment by bgruening** [comment]
Muchas gracias! :)

**Comment by bebatut** [comment]
I merged the PR #140 
Thanks a lot
