### ISSUE TITLE
GUIDELINES.md

### ISSUE THREAD

**Issue by bgruening** [bgruening/training-material#9]
We created a few issues over the last days, getting a sense of how we would like to structure the repo and what is recommended and not.
We need to collect this in a GUIDELINES.md file. Any help welcome.

**Comment by bgruening** [comment]
First version is here: https://github.com/bgruening/training-material/blob/master/GUIDELINES.md by Bérénice. A few things we need to include:

 - [ ] what is needed, what is nice to have
 - [ ] link to instructions on howto create a Galaxy flavor
 - [ ] link to instructions or instructions on how to create reveal.js slides, link to slides.com, other editors that can eport reveal.js slides
 - [ ] people should add themselves to the contributors list (or we do this manually once a month or so from the github log)

**Comment by bgruening** [comment]
xref: https://github.com/bgruening/training-material/pull/60

**Comment by bebatut** [comment]
The guidelines were extended in [`CONTRIBUTING.md`](https://github.com/bgruening/training-material/blob/master/CONTRIBUTING.md)
